<?php
/**
 * ZF1 legacy application
 *
 * @author     Ralf Eggert <ralf@travello.de>
 * @link       https://github.com/zf3buch/zf1legacy
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 */

$this->headTitle('Alle Katzenbabies!');
?>
<h1>Alle Katzenbabies!</h1>
<div class="row">
    <?php foreach ($this->allKitten as $kitten): ?>
        <?php
        $kittenLink = $this->url(
            [
                'module'     => 'kitten',
                'controller' => 'index',
                'action'     => 'show',
                'id'         => $kitten['id'],
            ]
        );
        ?>
        <div class="col-sm-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <a href="<?php echo $kittenLink; ?>">
                        <?php echo $kitten['name'] ?>
                    </a>
                </div>
                <div class="panel-body">
                    <a href="<?php echo $kittenLink; ?>">
                        <img src="<?php echo $kitten['image'] ?>"
                             class="img-responsive">
                    </a>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
</div>
