<?php
/**
 * ZF1 legacy application
 *
 * @author     Ralf Eggert <ralf@travello.de>
 * @link       https://github.com/zf3buch/zf1legacy
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 */

$this->headTitle()->setSeparator(' - ')->setAutoEscape(false);
$this->headTitle('ZF1legacy Application');

$this->headMeta()->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
$this->headMeta()->appendName(
    'viewport', 'width=device-width, initial-scale=1.0'
);

$this->headLink(
    [
        'rel'  => 'shortcut icon',
        'href' => '/assets/custom/img/favicon.ico'
    ]
);
$this->headLink()->appendStylesheet(
    '/assets/vendor/bootstrap/css/bootstrap.min.css'
);
$this->headLink()->appendStylesheet(
    '/assets/vendor/font-awesome/css/font-awesome.min.css'
);
$this->headLink()->appendStylesheet('/assets/custom/css/styles.css');

$this->inlineScript()->prependFile(
    '/assets/vendor/bootstrap/js/bootstrap.min.js', 'text/javascript'
);
$this->inlineScript()->prependFile(
    '/assets/vendor/jquery/jquery.min.js', 'text/javascript'
);
?>
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<?php echo $this->headScript() . "\n"; ?>
<?php echo $this->headMeta() . "\n"; ?>
<?php echo $this->headTitle() . "\n"; ?>
<?php echo $this->headLink() . "\n"; ?>
</head>
<body>
<div class="container">
    <header>
        <a href="<?php echo $this->url(
            ['module' => 'default'], null, true
        ); ?>">
            <img src="/assets/custom/img/logo.png" class="logo">
        </a>
    </header>
    <nav class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed"
                    data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">
                  Navigation umschalten
                </span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>
                    <a href="<?php echo $this->url(
                        ['module' => 'default'], null, true
                    ); ?>">
                        Startseite
                    </a>
                </li>
                <li>
                    <a href="<?php echo $this->url(
                        ['module' => 'kitten'], null, true
                    ); ?>">
                        Alle Katzenbabies
                    </a>
                </li>
            </ul>
        </div>
    </nav>
</div>
<div class="container">
    <?php echo $this->layout()->content; ?>
</div>
<footer id="footer">
    <div class="footer-top"></div>
    <div class="container">
        <div class="row">
            <div class="col-lg-4">
                <h4>
                    ZF1legacy Application
                </h4>
                <p>
                    Diese Anwendung basiert auf dem ZF1, bietet aber nur
                    wenige Funktionen. Anhand dieser soll die Migration zum
                    ZF3 erläutert werden.
                </p>
            </div>
            <div class="col-lg-4">
                <h4> Zend Framework Links </h4>
                <ul>
                    <li>
                        <a target="_blank"
                           href="http://framework.zend.com/">
                            Zend Framework Website
                        </a>
                    </li>
                    <li>
                        <a target="_blank"
                           href="http://modules.zendframework.com/">
                            Zend Framework 3 Module
                        </a>
                    </li>
                    <li>
                        <a target="_blank"
                           href="https://github.com/zendframework/">
                            Zend Framework Github
                        </a>
                    </li>
                </ul>
            </div>
            <div class="col-lg-4">
                <h4> ZF3buch Links </h4>
                <ul>
                    <li>
                        <a target="_blank"
                           href="http://www.zendframeworkbuch.de/">
                            Website zum ZF3 Buch
                        </a>
                    </li>
                    <li>
                        <a target="_blank"
                           href="https://github.com/zf3buch/zf1legacy">
                            GitHub Repository ZF1legacy Application
                        </a>
                    </li>
                    <li>
                        <a target="_blank" href="http://www.ralfeggert.de">
                            Homepage Ralf Eggert
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>
<?php echo $this->inlineScript(); ?>
</body>
</html>
