<?php
/**
 * ZF1 legacy application
 *
 * @author     Ralf Eggert <ralf@travello.de>
 * @link       https://github.com/zf3buch/zf1legacy
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 */

$this->headTitle($this->kitten['name']);
?>
<h1><?php echo $this->kitten['name']; ?></h1>
<p>
    <a href="<?php echo $this->url('kitten-list'); ?>"
       class="btn btn-success">
        Alle Katzenbabies
    </a>
</p>
<div class="panel panel-default">
    <div class="panel-heading">
        <?php echo $this->kitten['name'] ?>
    </div>
    <div class="panel-body">
        <img src="<?php echo $this->kitten['image'] ?>"
             class="img-responsive">
    </div>
</div>
